### PR TITLE
remove old grpc pins 

### PR DESCRIPTION
**Pull request by h-vetinari**
These are pretty badly outdated - let's rely on the global pinning. Also add myself to maintainers.

### CODE REVIEW

**Comment by h-vetinari** [comment]
@conda-forge-admin, please rerender

**Comment by h-vetinari** [comment]
@hmaarrfk 
Could it be that zlib might be a genuine host-dep of grpc after all?
The errors here and in #21 only show up in the cross-compilation builds, but I think that's because all the native builds will probably pick up the zlib from the build env?

**Comment by hmaarrfk** [comment]
It seem that this is due to some errors in cross compilation:
```
[ 59%] Linking CXX executable intercept
/home/conda/feedstock_root/build_artifacts/bear_1661699317670/_build_env/bin/../lib/gcc/aarch64-conda-linux-gnu/10.4.0/../../../../aarch64-conda-linux-gnu/bin/ld: /home/conda/feedstock_root/build_artifacts/bear_1661699317670/_build_env/lib/libz.so: error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status
```

it seem slike it is trying to find zlib pretty hard, and it found the one from `_build`

**Comment by hmaarrfk** [comment]
It seems suspect that they pull in some zlib themselves

**Comment by hmaarrfk** [comment]
ZLIB_SRC_DIR

**Comment by hmaarrfk** [comment]
https://github.com/rizsotto/Bear/blob/3b59c0ec14789b18443ee7fbbd55427867072a2b/.github/workflows/build_on_push.yml#L49

**Comment by hmaarrfk** [comment]
can you try to build with verbose?

**Comment by hmaarrfk** [comment]
can you build in verbose mode?

**Comment by h-vetinari** [comment]
> https://github.com/rizsotto/Bear/blob/3b59c0ec14789b18443ee7fbbd55427867072a2b/.github/workflows/build_on_push.yml#L49

Ah, I had been looking mainly at the CMakeList (was restricted to a phone until last night). Seems we might need to add zlib as a host dep?

**Comment by h-vetinari** [comment]
Doing `export VERBOSE=1` didn't yield any new information, see [these](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=559808&view=logs&j=517fe804-fa30-5dc2-1413-330699242c05&t=c10fa5f2-fdf6-5338-3bdb-c4bea7c23412) logs.

I added zlib as a host-dep now and think this should be merged. It seems a lot of packages were implicitly depending on zlib, and cleaning that up should not hold up other migrations (abseil, grpc, protobuf etc. are a gordian knot already as it is, and running into zlib issues in every second PR doesn't help).

**Comment by hmaarrfk** [comment]
```
2022-08-29T13:18:40.9386552Z WARNING (bear): run-exports library package conda-forge::libzlib-1.2.12-h166bdaf_2 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
```

I don't think bear depends on it at runtime. Maybe pkgconfig is misconfigured.

I mean, you are the one that merged grpc after we reverted it.... You have the power to undo it.

**Comment by h-vetinari** [comment]
> I mean, you are the one that merged grpc after we reverted it.... You have the power to undo it.

I'm not sure which reverted change you're referring to, but AFAICT, these issues come from https://github.com/conda-forge/grpc-cpp-feedstock/commit/88c34af31770534e09c6f33990a64343ecf7d313, which was your commit. Previously `grpc` brought along zlib anywhere it went, now it doesn't anymore, and we're running into that in several places.

**Comment by h-vetinari** [comment]
> I don't think bear depends on it at runtime. Maybe pkgconfig is misconfigured.

Or the conda-build analysis is misconfigured or not clever enough. Before adding zlib here, we were running into symbol errors while doing
```
[ 59%] Linking CXX executable intercept
```
which is a pretty strong indication (together with the usage in CI upstream) to me that it's needed.

**Comment by hmaarrfk** [comment]
I don't mean to play the blame game, but I recall both you and I having commits to the merge request which you clicked merge on.

I'm sorry if I wasn't so explicit in my "merge at will". I really meant "I don't have time to review too much, merge when you feel ok"

The fact that it is failing at the final linking step is not so much an indication of `bear` depending on zlib, but rather some incorrect linking flags.

In fact, grpc-cpp bulid 5 still lists `-lz` in its linking flags `grpc-cpp-1.46.4-h05bd8bd_5.tar.bz2`:

image

Please don't jump to conclusions too quickly. If you feel we aren't ready to remove the zlib build time dependencies from grpc run time dependencies, please leave them in. But it isn't because `bear` depends on it. 

The commit you linked to was reverted by yourself. It was then re-introced, by you and I in 213. I think we should revert 213.

Feedstocks implicitly depending on things is not a good reason to undo 213. But 213 not providing correct build files is.

**Comment by h-vetinari** [comment]
> I don't mean to play the blame game, but I recall both you and I having commits to the merge request which you clicked merge on.
> 
> I'm sorry if I wasn't so explicit in my "merge at will". I really meant "I don't have time to review too much, merge when you feel ok"

Neither was I trying to cast blame. My point was that the clean-up of the run-deps of grpc, while in itself important, is coming at an unfortunate time where I'm trying to clean up the state of several migrations & push them to conclusion.

The errors it uncovers (in the grpc link-surface, and other feedstocks who didn't declare the right host deps) are now overlaid with the already tricky migration work, and I would prefer to avoid that.

> The fact that it is failing at the final linking step is not so much an indication of `bear` depending on zlib, but rather some incorrect linking flags.
> 
> In fact, grpc-cpp bulid 5 still lists `-lz` in its linking flags `grpc-cpp-1.46.4-h05bd8bd_5.tar.bz2`:

OK, that sounds reasonable, ...

> Please don't jump to conclusions too quickly. If you feel we aren't ready to remove the zlib build time dependencies from grpc run time dependencies, please leave them in. But it isn't because `bear` depends on it.

... but I still think temporarily re-adding the run-deps, running through the migrations, and _then_ removing the run-deps would be a saner approach than trying to juggle all at once.

> The commit you linked to was reverted by yourself. It was then re-introced, by you and I in 213. I think we should revert 213.
> 
> Feedstocks implicitly depending on things is not a good reason to undo 213. But 213 not providing correct build files is.

I'm fine with marking the builds from 213 as broken, but I think it goes in the right direction. It did solve the situation for https://github.com/conda-forge/googleapis-cpp-feedstock/pull/35 for example. Windows+abseil still needs fixing, and so does pkgconfig now apparently, but that could be done on top?

**Comment by hmaarrfk** [comment]
> ... but I still think temporarily re-adding the run-deps, running through the migrations, and then removing the run-deps would be a saner approach than trying to juggle all at once.

You'll never get a "quiet time".

I think we got down to the point that grpc isn't quite correct. We should revert it. We can try again when we have time to try again.

**Comment by h-vetinari** [comment]
> I think we got down to the point that grpc isn't quite correct. We should revert it. We can try again when we have time to try again.

That reversion is OK, but get's us nowhere, because it just brings us to an even more broken state of link interface, and still leaves dependent feedstocks in the situation of not being rebuildable for the migrations. I'd have an easier time to go along with your position if you were willing to commit to rebuild all packages depending on grpc and sort out the rundep-related fallout within X (<2 weeks, say). The link interface stuff is part of that, and I only merged the respective PR (after working hard to fix it in the first place), because I'm trying to work around the consequences of that change you wanted.

We both have a respective change that's more important to us individually, but I'm not very good at fixing the fallout of yours, so if you cannot shepherd this through while you're (justifiably) busy with other things, why insist that the rundep-stuff _has to_ get solved before I can deal with the migrations? It has very little cost of solving it later.

> You'll never get a "quiet time".

And I'll counter that we fell behind on abseil, grpc & protobuf for various unrelated reasons, and that catching up on that is more important than the purely cf-internal cleanup of whether zlib is a run-dep or not.

**Comment by hmaarrfk** [comment]
> That reversion is OK, but gets us nowhere, because it just brings us to an even more broken state of link interface, and still leaves dependent feedstocks in the situation of not being rebuildable for the migrations

I don't understand why it leaves us in a "more broken" state. Because of the libprotobuf migration?

**Comment by h-vetinari** [comment]
> I don't understand why it leaves us in a "more broken" state. Because of the libprotobuf migration?

Removing the zlib rundep uncovered that grpc actually has it as a PUBLIC linkage, hence it would need to be a host dep for any package trying to link to grpc. This would be "solved" by re-adding zlib as a temporary rundep while reverting 213, but I've also seen missing openssl symbols in https://github.com/conda-forge/google-cloud-cpp-feedstock/pull/107 (the abseil stuff is not directly related to your commit but with the change of building against a static lib without run-exports on windows).

Don't get me wrong, downstream feedstocks should have their host deps correct, and grpc should have its link interface correct, and, and, and.... But that cleanup is really orthogonal to "let's update the existing & previously working recipes to a newer version", and I want to separate those two actions. The latter one should be pretty straight forward, and the former can IMO be done later.

**Comment by hmaarrfk** [comment]
Maybe i'm just sick today and can't really understand things. But i'm not too sure what you are expecting from me at this exact moment. This is disrupting builds. But it is not leaving users with broken packages on their machines. So for me, this is not super high priority.

We have discussed a few options:

1. Option 1. Revert PR 213 on all 3 branches of grpcio. Try to patch out zlib later.
2. Option 2. Add zlib as you go temporarily. Remember to remove it later.

These two are both acceptable for me. I lean more toward Option 1. But I don't have the time to execute on it, so I have to take a back seat to your judgement.

I'm going to try to submit a patch for Option 1: https://github.com/conda-forge/grpc-cpp-feedstock/pull/236 but I don't think I have time to propagate it to 1.47.x and 1.48.x

**Comment by h-vetinari** [comment]
> We have discussed a few options:
>   1. Option 1. Revert PR 213 on all 3 branches of grpcio. Try to patch out zlib later.
>   2. Option 2. Add zlib as you go temporarily. Remember to remove it later.

Option 3. would be to re-add zlib (and openssl) as a rundep to grpc, and remember to remove it later. That makes it only _one_ place to have to remember, rather than N.

> I'm going to try to submit a patch for Option 1: [conda-forge/grpc-cpp-feedstock#236](https://github.com/conda-forge/grpc-cpp-feedstock/pull/236) but I don't think I have time to propagate it to 1.47.x and 1.48.x

I can propagate it once we have something working.

**Comment by hmaarrfk** [comment]
Isn't option 3 and option 1 the same?

**Comment by h-vetinari** [comment]
> Isn't option 3 and option 1 the same?

The reversion is compatible with re-adding the run-deps (though the latter is possible without the former), but yeah, I noted in an edit that these two are compatible. I'm fine with the reversion, even though I think the patches are a step in the right direction (and the churn in going back & forth not my favourite). But I'll need more time how to set up some proper testing of the link interface and in the meantime your proposed PR is fine for me.

**Comment by hmaarrfk** [comment]
I guess feel free to continue the discussion: https://github.com/conda-forge/grpc-cpp-feedstock/pull/236

**Comment by h-vetinari** [comment]
@conda-forge/bear @hmaarrfk PTAL

This is green now, and I'd be willing to join as maintainer

**Review by mwittgen — APPROVED** [review]

**Comment by hmaarrfk** [comment]
Great work @h-vetinari

**Comment by hmaarrfk** [comment]
Thank you for you taking at a look and merging @mwittgen

**Pull request merged**
